module.exports = {
  content: ["./*.html", "./assets/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0e0e0e",
        "error-container": "#93000a",
        background: "#131313",
        "secondary-fixed": "#ffdea8",
        "outline-variant": "#37444b",
        "surface-container-low": "#1b1b1b",
        "surface-tint": "#2aa8ff",
        "surface-container-highest": "#353535",
        "on-surface-variant": "#b2c7d6",
        "secondary-fixed-dim": "#ffba20",
        "on-primary-container": "#004d7a",
        "surface-bright": "#393939",
        "on-secondary-container": "#6b4b00",
        "on-primary-fixed-variant": "#003a5a",
        "surface-variant": "#353535",
        error: "#ffb4ab",
        secondary: "#ffdb9d",
        primary: "#e5f5ff",
        "on-secondary-fixed": "#271900",
        "on-tertiary": "#442b10",
        tertiary: "#fff8f4",
        "on-tertiary-fixed": "#2c1701",
        "on-surface": "#e2e2e2",
        "primary-container": "#2aa8ff",
        "secondary-container": "#feb700",
        "surface-container-high": "#2a2a2a",
        surface: "#131313",
        "on-background": "#e2e2e2",
        outline: "#7e9096",
        "tertiary-fixed-dim": "#e7bf99",
        "surface-container": "#1f1f1f",
        "on-tertiary-container": "#7a5b3c",
        "on-secondary-fixed-variant": "#5e4200",
        "inverse-surface": "#e2e2e2",
        "on-primary": "#001927",
        "inverse-primary": "#1477b8",
        "on-error": "#690005",
        "tertiary-fixed": "#ffdcbd",
        "primary-fixed": "#70c8ff",
        "primary-fixed-dim": "#2aa8ff",
        "on-primary-fixed": "#001927",
        "surface-dim": "#131313",
        "on-tertiary-fixed-variant": "#5d4124",
        "inverse-on-surface": "#303030",
        "tertiary-container": "#ffd5ae",
        "on-secondary": "#412d00",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "64px",
        md: "24px",
        xs: "8px",
        lg: "40px",
        "margin-mobile": "20px",
        gutter: "1px",
        sm: "16px",
        "margin-desktop": "48px",
        base: "4px",
      },
      fontFamily: {
        "headline-lg": ["Space Mono", "monospace"],
        "headline-sm": ["Space Mono", "monospace"],
        "headline-md": ["Space Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Space Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-md": ["Geist", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
